[package]
name = "push_swap_rpv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12.1"
clap = { version = "4.3.11", features=["derive", "string"] }
rand = "0.8.5"
rayon = "1.7.0"
